'use client'

import Link from 'next/link'
import { MoreHorizontal, Pencil, Plus, Search, Utensils, X } from 'lucide-react'
import { useState } from 'react'

type Table = { id: string, name_or_number: string, capacity: number, status: string }
type Order = { id: string, order_number: number }
type Action = (data: FormData) => void | Promise<void>

type Props = {
    tables: Table[]
    orderByTable: Record<string, Order>
    archived: boolean
    totalTables: number
    availableCount: number
    occupiedCount: number
    totalCapacity: number
    createTable: Action
    updateTable: Action
    archiveTable: Action
    restoreTable: Action
}

export default function RestaurantTablesUI({ tables, orderByTable, archived, totalTables, availableCount, occupiedCount, totalCapacity, createTable, updateTable, archiveTable, restoreTable }: Props) {
    const [showAdd, setShowAdd] = useState(false)
    const [editing, setEditing] = useState<Table | null>(null)
    const [menuId, setMenuId] = useState<string | null>(null)
    const [search, setSearch] = useState('')
    const [status, setStatus] = useState('all')
    const query = search.trim().toLowerCase()
    const filtered = tables.filter(table => (!query || table.name_or_number.toLowerCase().includes(query)) && (status === 'all' || table.status === status))

    return <div className="space-y-6" onClick={() => menuId && setMenuId(null)}>
        <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-orange-600">Floor management</p><h1 className="mt-1 text-3xl font-black tracking-tight text-gray-950 dark:text-white">Dining Tables</h1><p className="mt-1 text-sm text-gray-500">Manage table availability, capacity and active dine-in orders.</p></div><div className="flex flex-wrap gap-2"><Link href="/dashboard/tables" className={!archived ? 'rounded-xl bg-orange-600 px-3.5 py-2 text-sm font-bold text-white' : 'rounded-xl border border-gray-200 px-3.5 py-2 text-sm font-semibold dark:border-gray-700'}>Active</Link><Link href="/dashboard/tables?archived=true" className={archived ? 'rounded-xl bg-orange-600 px-3.5 py-2 text-sm font-bold text-white' : 'rounded-xl border border-gray-200 px-3.5 py-2 text-sm font-semibold dark:border-gray-700'}>Archived</Link><Link href="/dashboard/orders" className="rounded-xl bg-blue-600 px-3.5 py-2 text-sm font-bold text-white hover:bg-blue-700">Start order</Link></div></header>

        <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Summary label="Total Tables" value={String(totalTables)} /><Summary label="Available" value={String(availableCount)} /><Summary label="Occupied" value={String(occupiedCount)} /><Summary label="Total Capacity" value={`${totalCapacity} seats`} /></section>

        <section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900">
            <div className="flex flex-col gap-3 border-b border-gray-100 p-4 dark:border-gray-800 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold text-gray-950 dark:text-white">{archived ? 'Archived tables' : 'Floor plan'}</h2><p className="text-xs text-gray-500">{filtered.length} table{filtered.length === 1 ? '' : 's'} in this view</p></div>{!archived && <button type="button" onClick={() => setShowAdd(true)} className="inline-flex items-center justify-center rounded-xl bg-orange-600 px-3.5 py-2 text-sm font-bold text-white hover:bg-orange-700"><Plus size={16} className="mr-1.5" />Add table</button>}</div>
            <div className="grid gap-2 border-b border-gray-100 p-4 dark:border-gray-800 sm:grid-cols-[minmax(0,1fr)_170px]"><label className="relative block"><Search size={16} className="pointer-events-none absolute left-3 top-3 text-gray-400" /><span className="sr-only">Search tables</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search tables..." className="w-full rounded-xl border border-gray-200 bg-gray-50 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100 dark:border-gray-700 dark:bg-gray-800 dark:text-white" /></label><label><span className="sr-only">Filter table status</span><select value={status} onChange={event => setStatus(event.target.value)} className="w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm dark:border-gray-700 dark:bg-gray-800 dark:text-white"><option value="all">All statuses</option><option value="available">Available</option><option value="occupied">Occupied</option></select></label></div>
            {filtered.length ? <><div className="hidden overflow-x-auto sm:block"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-[11px] font-bold uppercase tracking-wider text-gray-500 dark:bg-gray-800/60"><tr><th className="px-5 py-3">Table</th><th className="px-5 py-3">Capacity</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Current order</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-gray-800">{filtered.map(table => <DesktopRow key={table.id} table={table} order={orderByTable[table.id]} archived={archived} menuId={menuId} setMenuId={setMenuId} onEdit={() => setEditing(table)} archiveTable={archiveTable} restoreTable={restoreTable} />)}</tbody></table></div><div className="divide-y divide-gray-100 dark:divide-gray-800 sm:hidden">{filtered.map(table => <MobileRow key={table.id} table={table} order={orderByTable[table.id]} archived={archived} menuId={menuId} setMenuId={setMenuId} onEdit={() => setEditing(table)} archiveTable={archiveTable} restoreTable={restoreTable} />)}</div></> : <div className="px-5 py-14 text-center"><div className="mx-auto mb-3 flex h-11 w-11 items-center justify-center rounded-full bg-orange-50 text-orange-600 dark:bg-orange-950/30"><Utensils size={20} /></div><h3 className="font-bold text-gray-900 dark:text-white">{tables.length ? 'No matching tables' : archived ? 'No archived tables' : 'No tables yet'}</h3><p className="mt-1 text-sm text-gray-500">{tables.length ? 'Try a different search or status filter.' : archived ? 'Archived tables will appear here.' : 'Add dining tables to start managing dine-in orders.'}</p>{!tables.length && !archived && <button type="button" onClick={() => setShowAdd(true)} className="mt-4 rounded-lg bg-orange-600 px-3 py-2 text-sm font-semibold text-white">Add first table</button>}</div>}
        </section>
        {showAdd && <TableDialog title="Add table" submitLabel="Add table" action={createTable} onClose={() => setShowAdd(false)} />}
        {editing && <TableDialog title="Edit table" submitLabel="Save changes" action={updateTable} table={editing} onClose={() => setEditing(null)} />}
    </div>
}

function Summary({ label, value }: { label: string, value: string }) { return <div className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-900"><p className="text-xs font-semibold text-gray-500">{label}</p><p className="mt-1 text-xl font-black tracking-tight text-gray-950 dark:text-white">{value}</p></div> }

function StatusBadge({ status }: { status: string }) { const occupied = status === 'occupied'; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${occupied ? 'bg-orange-50 text-orange-700 dark:bg-orange-950/30 dark:text-orange-300' : 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300'}`}>{occupied ? 'Occupied' : status === 'inactive' ? 'Archived' : 'Available'}</span> }

function Actions({ table, archived, menuId, setMenuId, onEdit, archiveTable, restoreTable }: { table: Table, archived: boolean, menuId: string | null, setMenuId: (id: string | null) => void, onEdit: () => void, archiveTable: Action, restoreTable: Action }) { return <div className="relative flex items-center justify-end gap-2" onClick={event => event.stopPropagation()}>{!archived && <button type="button" onClick={onEdit} className="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 px-2.5 py-1.5 text-xs font-semibold text-gray-700 hover:border-blue-300 hover:text-blue-600 dark:border-gray-700 dark:text-gray-300"><Pencil size={14} />Edit</button>}<button type="button" title="More table actions" aria-label={`More actions for ${table.name_or_number}`} onClick={() => setMenuId(menuId === table.id ? null : table.id)} className="rounded-lg border border-gray-200 p-1.5 text-gray-500 hover:text-gray-900 dark:border-gray-700 dark:hover:text-white"><MoreHorizontal size={16} /></button>{menuId === table.id && <div className="absolute right-0 top-9 z-10 w-40 rounded-xl border border-gray-200 bg-white p-1.5 shadow-lg dark:border-gray-700 dark:bg-gray-900">{archived ? <form action={restoreTable}><input type="hidden" name="id" value={table.id} /><button className="w-full rounded-lg px-3 py-2 text-left text-xs font-semibold text-emerald-600 hover:bg-emerald-50">Restore table</button></form> : <form action={archiveTable}><input type="hidden" name="id" value={table.id} /><button className="w-full rounded-lg px-3 py-2 text-left text-xs font-semibold text-red-600 hover:bg-red-50">Archive table</button></form>}</div>}</div> }

function OrderLink({ order }: { order?: Order }) { return order ? <Link href={`/dashboard/orders?order=${order.id}`} className="text-sm font-semibold text-blue-600 hover:underline">Open order <span className="text-gray-500">#{order.order_number}</span></Link> : <span className="text-sm text-gray-400">—</span> }

function DesktopRow({ table, order, archived, menuId, setMenuId, onEdit, archiveTable, restoreTable }: { table: Table, order?: Order, archived: boolean, menuId: string | null, setMenuId: (id: string | null) => void, onEdit: () => void, archiveTable: Action, restoreTable: Action }) { return <tr className="transition hover:bg-gray-50/80 dark:hover:bg-gray-800/40"><td className="px-5 py-4 font-bold text-gray-950 dark:text-white">{table.name_or_number}</td><td className="px-5 py-4 text-gray-500">{table.capacity} seats</td><td className="px-5 py-4"><StatusBadge status={table.status} /></td><td className="px-5 py-4"><OrderLink order={order} /></td><td className="px-5 py-4"><Actions table={table} archived={archived} menuId={menuId} setMenuId={setMenuId} onEdit={onEdit} archiveTable={archiveTable} restoreTable={restoreTable} /></td></tr> }

function MobileRow({ table, order, archived, menuId, setMenuId, onEdit, archiveTable, restoreTable }: { table: Table, order?: Order, archived: boolean, menuId: string | null, setMenuId: (id: string | null) => void, onEdit: () => void, archiveTable: Action, restoreTable: Action }) { return <div className="space-y-3 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-gray-950 dark:text-white">{table.name_or_number}</p><p className="mt-1 text-xs text-gray-500">{table.capacity} seats</p></div><StatusBadge status={table.status} /></div>{order && <div><p className="mb-1 text-[11px] font-semibold uppercase tracking-wide text-gray-400">Current order</p><OrderLink order={order} /></div>}<Actions table={table} archived={archived} menuId={menuId} setMenuId={setMenuId} onEdit={onEdit} archiveTable={archiveTable} restoreTable={restoreTable} /></div> }

function TableDialog({ title, submitLabel, action, table, onClose }: { title: string, submitLabel: string, action: Action, table?: Table, onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-950/40 p-4" role="dialog" aria-modal="true" aria-label={title} onClick={onClose}><form action={action} onClick={event => event.stopPropagation()} className="w-full max-w-md rounded-2xl border border-gray-200 bg-white p-5 shadow-2xl dark:border-gray-700 dark:bg-gray-900"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-orange-600">Table management</p><h2 className="mt-1 text-xl font-black text-gray-950 dark:text-white">{title}</h2></div><button type="button" onClick={onClose} aria-label="Close dialog" className="rounded-lg p-2 text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800"><X size={18} /></button></div>{table && <input type="hidden" name="id" value={table.id} />}<div className="grid gap-4"><label className="text-xs font-semibold uppercase tracking-wide text-gray-500">Table name / number *<input name="name" required defaultValue={table?.name_or_number} placeholder="e.g. Table 5" className="mt-1 w-full rounded-xl border border-gray-200 bg-gray-50 p-2.5 text-sm dark:border-gray-700 dark:bg-gray-800 dark:text-white" /></label><label className="text-xs font-semibold uppercase tracking-wide text-gray-500">Capacity *<input name="capacity" type="number" min="1" step="1" required defaultValue={table?.capacity} placeholder="4" className="mt-1 w-full rounded-xl border border-gray-200 bg-gray-50 p-2.5 text-sm dark:border-gray-700 dark:bg-gray-800 dark:text-white" /></label>{table && <label className="text-xs font-semibold uppercase tracking-wide text-gray-500">Status<select name="status" defaultValue={table.status} className="mt-1 w-full rounded-xl border border-gray-200 bg-gray-50 p-2.5 text-sm dark:border-gray-700 dark:bg-gray-800 dark:text-white"><option value="available">Available</option><option value="occupied">Occupied</option><option value="reserved">Reserved</option><option value="inactive">Unavailable</option></select></label>}</div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border border-gray-200 px-4 py-2 text-sm font-semibold dark:border-gray-700">Cancel</button><button type="submit" className="rounded-xl bg-orange-600 px-4 py-2 text-sm font-bold text-white">{submitLabel}</button></div></form></div> }