ALTER TABLE public.restaurant_order_items ALTER COLUMN unit_price TYPE numeric(14,4);

ALTER TABLE public.restaurant_orders
  ADD COLUMN order_number bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN guest_count integer,
  ADD CONSTRAINT restaurant_orders_order_number_key UNIQUE(order_number),
  ADD CONSTRAINT restaurant_orders_guest_count_check CHECK(guest_count IS NULL OR guest_count>0);

DROP FUNCTION IF EXISTS public.create_restaurant_order(text,uuid,text);
CREATE FUNCTION public.create_restaurant_order(p_order_type text,p_table_id uuid,p_guest_count integer,p_notes text)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE s uuid:=public.get_user_shop_id(); o uuid;
BEGIN
 IF s IS NULL OR NOT public.industry_module_enabled(s,'restaurant_orders') THEN RAISE EXCEPTION 'unauthorized module'; END IF;
 IF p_order_type NOT IN('dine_in','takeaway') OR (p_order_type='dine_in' AND p_table_id IS NULL) OR (p_order_type='takeaway' AND p_table_id IS NOT NULL) OR (p_guest_count IS NOT NULL AND p_guest_count<1) THEN RAISE EXCEPTION 'invalid order details'; END IF;
 IF p_table_id IS NOT NULL THEN
  PERFORM 1 FROM public.restaurant_tables WHERE id=p_table_id AND shop_id=s AND status='available' FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'table is unavailable or belongs to another shop'; END IF;
 END IF;
 INSERT INTO public.restaurant_orders(shop_id,table_id,order_type,guest_count,notes,status) VALUES(s,p_table_id,p_order_type,p_guest_count,NULLIF(trim(p_notes),''),'pending') RETURNING id INTO o;
 IF p_table_id IS NOT NULL THEN UPDATE public.restaurant_tables SET status='occupied' WHERE id=p_table_id AND shop_id=s; END IF;
 RETURN o;
END $$;

CREATE FUNCTION public.adjust_restaurant_order_item(p_order_id uuid,p_product_id uuid,p_delta integer,p_notes text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE s uuid:=public.get_user_shop_id(); current_quantity numeric; price numeric;
BEGIN
 IF s IS NULL OR NOT public.industry_module_enabled(s,'restaurant_orders') THEN RAISE EXCEPTION 'unauthorized module'; END IF;
 IF p_delta=0 THEN RAISE EXCEPTION 'quantity adjustment cannot be zero'; END IF;
 PERFORM 1 FROM public.restaurant_orders WHERE id=p_order_id AND shop_id=s AND sale_id IS NULL AND status='pending' FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'open order not found'; END IF;
 SELECT selling_price INTO price FROM public.products WHERE id=p_product_id AND shop_id=s AND is_active FOR SHARE;
 IF price IS NULL THEN RAISE EXCEPTION 'active menu item not found'; END IF;
 SELECT quantity INTO current_quantity FROM public.restaurant_order_items WHERE order_id=p_order_id AND product_id=p_product_id AND shop_id=s FOR UPDATE;
 IF current_quantity IS NULL THEN
  IF p_delta<1 THEN RAISE EXCEPTION 'order item not found'; END IF;
  INSERT INTO public.restaurant_order_items(shop_id,order_id,product_id,quantity,unit_price,notes) VALUES(s,p_order_id,p_product_id,p_delta,price,NULLIF(trim(p_notes),''));
 ELSIF current_quantity+p_delta<=0 THEN
  DELETE FROM public.restaurant_order_items WHERE order_id=p_order_id AND product_id=p_product_id AND shop_id=s;
 ELSE
  UPDATE public.restaurant_order_items SET quantity=current_quantity+p_delta,notes=COALESCE(NULLIF(trim(p_notes),''),notes) WHERE order_id=p_order_id AND product_id=p_product_id AND shop_id=s;
 END IF;
 UPDATE public.restaurant_orders SET total_amount=(SELECT COALESCE(sum(quantity*unit_price),0) FROM public.restaurant_order_items WHERE order_id=p_order_id),updated_at=now() WHERE id=p_order_id AND shop_id=s;
END $$;

CREATE OR REPLACE FUNCTION public.complete_restaurant_order(p_order_id uuid,p_payment_method text)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE s uuid:=public.get_user_shop_id(); sale uuid; total numeric; table_ref uuid; item record;
BEGIN
 IF s IS NULL OR NOT public.industry_module_enabled(s,'restaurant_orders') THEN RAISE EXCEPTION 'unauthorized module'; END IF;
 SELECT table_id,total_amount INTO table_ref,total FROM public.restaurant_orders WHERE id=p_order_id AND shop_id=s AND status='pending' AND sale_id IS NULL FOR UPDATE;
 IF NOT FOUND OR total<=0 THEN RAISE EXCEPTION 'open order has no payable items or is already paid'; END IF;
 FOR item IN SELECT oi.quantity,p.name,p.quantity stock FROM public.restaurant_order_items oi JOIN public.products p ON p.id=oi.product_id AND p.shop_id=s WHERE oi.order_id=p_order_id FOR UPDATE OF p
 LOOP IF item.stock<item.quantity THEN RAISE EXCEPTION 'insufficient stock for %',item.name; END IF; END LOOP;
 INSERT INTO public.sales(shop_id,user_id,customer_name,subtotal,discount,tax,total_amount,status) VALUES(s,auth.uid(),'Restaurant Guest',total,0,0,total,'completed') RETURNING id INTO sale;
 INSERT INTO public.sale_items(sale_id,shop_id,product_id,product_name,quantity,unit_price,total_price)
 SELECT sale,s,oi.product_id,CASE WHEN oi.notes LIKE 'Deal: %' THEN p.name||' ('||split_part(oi.notes,' - ',1)||')' ELSE p.name END,oi.quantity,oi.unit_price,oi.quantity*oi.unit_price FROM public.restaurant_order_items oi JOIN public.products p ON p.id=oi.product_id WHERE oi.order_id=p_order_id;
 UPDATE public.products p SET quantity=p.quantity-oi.quantity FROM public.restaurant_order_items oi WHERE oi.order_id=p_order_id AND p.id=oi.product_id AND p.shop_id=s;
 INSERT INTO public.payments(sale_id,shop_id,amount,method) VALUES(sale,s,total,p_payment_method);
 UPDATE public.restaurant_orders SET sale_id=sale,status='completed',updated_at=now() WHERE id=p_order_id AND shop_id=s AND sale_id IS NULL;
 IF NOT FOUND THEN RAISE EXCEPTION 'order was already paid'; END IF;
 IF table_ref IS NOT NULL THEN UPDATE public.restaurant_tables SET status='available' WHERE id=table_ref AND shop_id=s; END IF;
 RETURN sale;
END $$;
CREATE OR REPLACE FUNCTION public.shop_type_default_modules(p_shop_type text)
RETURNS text[] LANGUAGE plpgsql STABLE SET search_path='' AS $$
BEGIN
  CASE lower(COALESCE(p_shop_type,'retail'))
    WHEN 'restaurant' THEN RETURN ARRAY['dashboard','pos','sales','menu','restaurant_tables','restaurant_orders','customers','expenses','reports'];
    WHEN 'pharmacy' THEN RETURN ARRAY['dashboard','pos','products','medicines','customers','categories','medicine_batches','medicine_expiry','prescriptions','suppliers','purchases','sales','reports'];
    WHEN 'grocery' THEN RETURN ARRAY['dashboard','pos','products','categories','inventory','sales','purchases','suppliers','customers','expenses','reports','medicine_batches','medicine_expiry'];
    ELSE RETURN ARRAY['dashboard','pos','products','categories','inventory','sales','purchases','suppliers','customers','expenses','reports'];
  END CASE;
END $$;

DO $$
DECLARE shop_record record;
BEGIN
  FOR shop_record IN SELECT id FROM public.shops WHERE shop_type='restaurant' LOOP
    PERFORM public.seed_shop_modules(shop_record.id,'restaurant');
  END LOOP;
END $$;
CREATE TABLE public.restaurant_deals (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), shop_id uuid NOT NULL REFERENCES public.shops(id) ON DELETE CASCADE,
 name text NOT NULL CHECK(length(trim(name))>0), description text, deal_price numeric(12,2) NOT NULL CHECK(deal_price>=0),
 is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(shop_id,name)
);
CREATE TABLE public.restaurant_deal_items (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), shop_id uuid NOT NULL REFERENCES public.shops(id) ON DELETE CASCADE,
 deal_id uuid NOT NULL REFERENCES public.restaurant_deals(id) ON DELETE CASCADE,
 product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
 quantity numeric(10,2) NOT NULL CHECK(quantity>0), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(deal_id,product_id)
);
CREATE INDEX restaurant_deals_shop_active ON public.restaurant_deals(shop_id,is_active,name);
CREATE INDEX restaurant_deal_items_shop_deal ON public.restaurant_deal_items(shop_id,deal_id);
ALTER TABLE public.restaurant_deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurant_deal_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Members read restaurant deals" ON public.restaurant_deals FOR SELECT TO authenticated USING(public.industry_module_enabled(shop_id,'menu') OR public.industry_module_enabled(shop_id,'restaurant_orders'));
CREATE POLICY "Members read restaurant deal items" ON public.restaurant_deal_items FOR SELECT TO authenticated USING(public.industry_module_enabled(shop_id,'menu') OR public.industry_module_enabled(shop_id,'restaurant_orders'));

CREATE FUNCTION public.validate_restaurant_deal_reference() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$
DECLARE ds uuid; ps uuid;
BEGIN
 SELECT shop_id INTO ds FROM public.restaurant_deals WHERE id=NEW.deal_id;
 SELECT shop_id INTO ps FROM public.products WHERE id=NEW.product_id AND is_active;
 IF ds IS NULL OR ps IS NULL OR NEW.shop_id<>ds OR NEW.shop_id<>ps THEN RAISE EXCEPTION 'deal component belongs to another shop or is unavailable'; END IF;
 RETURN NEW;
END $$;
CREATE FUNCTION public.prevent_restaurant_deal_shop_change() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$
BEGIN IF NEW.shop_id IS DISTINCT FROM OLD.shop_id THEN RAISE EXCEPTION 'shop_id is immutable'; END IF; RETURN NEW; END $$;
CREATE TRIGGER restaurant_deals_shop_immutable BEFORE UPDATE OF shop_id ON public.restaurant_deals FOR EACH ROW EXECUTE FUNCTION public.prevent_restaurant_deal_shop_change();
CREATE TRIGGER restaurant_deal_items_shop_immutable BEFORE UPDATE OF shop_id ON public.restaurant_deal_items FOR EACH ROW EXECUTE FUNCTION public.prevent_restaurant_deal_shop_change();
CREATE TRIGGER restaurant_deal_items_validate BEFORE INSERT OR UPDATE ON public.restaurant_deal_items FOR EACH ROW EXECUTE FUNCTION public.validate_restaurant_deal_reference();

CREATE FUNCTION public.manage_restaurant_deal(p_operation text,p_deal_id uuid,p_name text,p_description text,p_deal_price numeric,p_product_ids uuid[],p_quantities numeric[])
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE s uuid:=public.get_user_shop_id(); d uuid; i integer;
BEGIN
 IF s IS NULL OR NOT public.industry_module_enabled(s,'menu') THEN RAISE EXCEPTION 'unauthorized module'; END IF;
 IF p_operation='archive' THEN UPDATE public.restaurant_deals SET is_active=false,updated_at=now() WHERE id=p_deal_id AND shop_id=s AND is_active RETURNING id INTO d; IF d IS NULL THEN RAISE EXCEPTION 'active deal not found'; END IF; RETURN d; END IF;
 IF p_operation NOT IN('create','update') OR length(trim(COALESCE(p_name,'')))=0 OR p_deal_price<0 OR COALESCE(array_length(p_product_ids,1),0)=0 OR array_length(p_product_ids,1)<>array_length(p_quantities,1) THEN RAISE EXCEPTION 'invalid deal details'; END IF;
 IF EXISTS(SELECT 1 FROM generate_subscripts(p_quantities,1) x WHERE p_quantities[x]<=0) THEN RAISE EXCEPTION 'invalid deal quantity'; END IF;
 IF (SELECT count(*) FROM public.products WHERE shop_id=s AND is_active AND id=ANY(p_product_ids))<>array_length(p_product_ids,1) OR (SELECT count(DISTINCT x) FROM unnest(p_product_ids)x)<>array_length(p_product_ids,1) THEN RAISE EXCEPTION 'deal contains unavailable, duplicate, or cross-shop products'; END IF;
 IF p_operation='create' THEN INSERT INTO public.restaurant_deals(shop_id,name,description,deal_price) VALUES(s,trim(p_name),NULLIF(trim(p_description),''),p_deal_price) RETURNING id INTO d;
 ELSE UPDATE public.restaurant_deals SET name=trim(p_name),description=NULLIF(trim(p_description),''),deal_price=p_deal_price,updated_at=now() WHERE id=p_deal_id AND shop_id=s RETURNING id INTO d; IF d IS NULL THEN RAISE EXCEPTION 'deal not found'; END IF; DELETE FROM public.restaurant_deal_items WHERE deal_id=d AND shop_id=s; END IF;
 FOR i IN 1..array_length(p_product_ids,1) LOOP INSERT INTO public.restaurant_deal_items(shop_id,deal_id,product_id,quantity) VALUES(s,d,p_product_ids[i],p_quantities[i]); END LOOP;
 RETURN d;
END $$;

CREATE FUNCTION public.set_restaurant_deal_active(p_deal_id uuid,p_active boolean) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE s uuid:=public.get_user_shop_id(); BEGIN
 IF s IS NULL OR NOT public.industry_module_enabled(s,'menu') THEN RAISE EXCEPTION 'unauthorized module'; END IF;
 UPDATE public.restaurant_deals SET is_active=p_active,updated_at=now() WHERE id=p_deal_id AND shop_id=s; IF NOT FOUND THEN RAISE EXCEPTION 'deal not found'; END IF;
END $$;

CREATE FUNCTION public.add_restaurant_deal_to_order(p_order_id uuid,p_deal_id uuid,p_quantity integer,p_notes text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE
 s uuid:=public.get_user_shop_id(); d public.restaurant_deals%ROWTYPE; c record; regular numeric;
 line_quantity numeric; line_total numeric; allocated numeric:=0; component_index integer:=0; component_count integer;
BEGIN
 IF s IS NULL OR NOT public.industry_module_enabled(s,'restaurant_orders') THEN RAISE EXCEPTION 'unauthorized module'; END IF;
 IF p_quantity<1 THEN RAISE EXCEPTION 'deal quantity must be positive'; END IF;
 PERFORM 1 FROM public.restaurant_orders WHERE id=p_order_id AND shop_id=s AND sale_id IS NULL AND status='pending' FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'active order not found'; END IF;
 SELECT * INTO d FROM public.restaurant_deals WHERE id=p_deal_id AND shop_id=s AND is_active FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'active deal not found'; END IF;
 SELECT sum(di.quantity*p.selling_price),count(*) INTO regular,component_count FROM public.restaurant_deal_items di JOIN public.products p ON p.id=di.product_id AND p.shop_id=s AND p.is_active WHERE di.deal_id=d.id;
 IF regular IS NULL OR regular<=0 OR component_count=0 THEN RAISE EXCEPTION 'deal has no sellable components'; END IF;
 FOR c IN SELECT di.product_id,di.quantity,p.selling_price FROM public.restaurant_deal_items di JOIN public.products p ON p.id=di.product_id AND p.shop_id=s AND p.is_active WHERE di.deal_id=d.id ORDER BY di.id LOOP
  component_index:=component_index+1;
  line_quantity:=c.quantity*p_quantity;
  IF component_index=component_count THEN line_total:=d.deal_price*p_quantity-allocated;
  ELSE line_total:=round(d.deal_price*p_quantity*(c.quantity*c.selling_price/regular),4); allocated:=allocated+line_total; END IF;
  INSERT INTO public.restaurant_order_items(shop_id,order_id,product_id,quantity,unit_price,notes)
  VALUES(s,p_order_id,c.product_id,line_quantity,line_total/line_quantity,'Deal: '||d.name||CASE WHEN NULLIF(trim(p_notes),'') IS NULL THEN '' ELSE ' - '||trim(p_notes) END)
  ON CONFLICT(order_id,product_id) DO UPDATE SET unit_price=(public.restaurant_order_items.quantity*public.restaurant_order_items.unit_price+EXCLUDED.quantity*EXCLUDED.unit_price)/(public.restaurant_order_items.quantity+EXCLUDED.quantity),quantity=public.restaurant_order_items.quantity+EXCLUDED.quantity,notes=concat_ws(' | ',public.restaurant_order_items.notes,EXCLUDED.notes);
 END LOOP;
 UPDATE public.restaurant_orders SET total_amount=(SELECT COALESCE(sum(oi.quantity*oi.unit_price),0) FROM public.restaurant_order_items oi WHERE order_id=p_order_id),updated_at=now() WHERE id=p_order_id;
END $$;

REVOKE ALL ON public.restaurant_deals,public.restaurant_deal_items FROM anon;
REVOKE INSERT,UPDATE,DELETE ON public.restaurant_deals,public.restaurant_deal_items FROM authenticated;
GRANT SELECT ON public.restaurant_deals,public.restaurant_deal_items TO authenticated;
GRANT ALL ON public.restaurant_deals,public.restaurant_deal_items TO service_role;
REVOKE ALL ON FUNCTION public.manage_restaurant_deal(text,uuid,text,text,numeric,uuid[],numeric[]) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.set_restaurant_deal_active(uuid,boolean) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.add_restaurant_deal_to_order(uuid,uuid,integer,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.manage_restaurant_deal(text,uuid,text,text,numeric,uuid[],numeric[]) TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.set_restaurant_deal_active(uuid,boolean) TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.add_restaurant_deal_to_order(uuid,uuid,integer,text) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.validate_restaurant_deal_reference() FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.prevent_restaurant_deal_shop_change() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.validate_restaurant_deal_reference() TO service_role;
GRANT EXECUTE ON FUNCTION public.prevent_restaurant_deal_shop_change() TO service_role;

REVOKE ALL ON FUNCTION public.create_restaurant_order(text,uuid,integer,text) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.adjust_restaurant_order_item(uuid,uuid,integer,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.create_restaurant_order(text,uuid,integer,text) TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.adjust_restaurant_order_item(uuid,uuid,integer,text) TO authenticated,service_role;
